JaniakMeble/JaniakMeble/Models/Dodatki.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class Dodatki
    {
        [Key]
        public int ID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Zdjecie zejecie { get; set; }
        public List<Tag> tagi { get; set; }
        public Dodatki()
        {
            tagi = new List<Tag>();
        }

    }
}

JaniakMeble/JaniakMeble/Models/Kategoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class Kategoria
    {
        [Key]
        public int ID { get; set; }
        public string nazwa { get; set; }
        public string link { get; set; }
        public Zdjecie zdjecie { get; set; }
        public List<Tag> tagi { get; set; }
        public Kategoria()
        {
            tagi = new List<Tag>();
        }

    }
}

JaniakMeble/JaniakMeble/Models/Mebel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class Mebel
    {
        [Key]
        public int ID { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public string wymiary { get; set; }
        public List<Zdjecie> zdjecia { get; set; }
        public List<Dodatki> dodatki { get; set; }
        public List<Tag> tagi { get; set; }
        public Mebel()
        {
            zdjecia = new List<Zdjecie>();
            dodatki = new List<Dodatki>();
            tagi = new List<Tag>();

        }
        
    }
}

JaniakMeble/JaniakMeble/Models/StronaTematyczna.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class StronaTematyczna
    {
        [Key]
        public int ID { get; set; }
        public string tekstHTML { get; set; }
    }
}

JaniakMeble/JaniakMeble/Models/Tag.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class Tag
    {
        [Key]
        public int ID { get; set; }
        public string tag { get; set; }
    }
}

JaniakMeble/JaniakMeble/Models/Zdjecie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace JaniakMeble.Models
{
    public class Zdjecie
    {
        [Key]
        public int ID { get; set; }
        public string link { get; set; }
        public List<Tag> tagi { get; set; }
        public Zdjecie()
        {
            tagi = new List<Tag>();
        }
    }
}

JaniakMeble/JaniakMeble/Controllers/CatalogController.cs
using JaniakMeble.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JaniakMeble.Controllers
{
    public class CatalogController : Controller
    {
        // GET: Catalog
        public ActionResult Index()
        {

            var listaKatalogow = myDAL.GetAllCatalogs();
            return View(listaKatalogow);
        }


        public ActionResult Details(string id)
        {
            var katalog = myDAL.GetCatalog(id);
            return View(katalog);
        }

    }
}

JaniakMeble/JaniakMeble/Controllers/HomeController.cs
using JaniakMeble.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JaniakMeble.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        //public ActionResult Index()
        //{           
        //    StronyTematyczne str2 = new StronyTematyczne();
        //    using (var db = new janiakmeble_6Entities())
        //    {
        //        var strona = from str in db.StronyTematyczne
        //                     where str.nazwa == "Strona główna"
        //                     select str;
        //        foreach (var a in strona)
        //        {
        //            str2 = a;
        //        }
        //        ViewBag.Title = str2.nazwa;
        //        ViewBag.Content = str2.tekstHTML.Replace("~","..");
        //        ViewBag.Route = "Home";

        //        return View();
        //    }
        //}

        public ActionResult Index(string id)
        {
            if (id == null) id = "Strona główna";
            StronyTematyczne str2 = new StronyTematyczne();
            using (var db = new janiakmeble_6Entities())
            {
                var strona = from str in db.StronyTematyczne
                             where str.nazwa == id
                             select str;
                foreach (var a in strona)
                {
                    str2 = a;
                }
                ViewBag.Title = str2.nazwa;
                ViewBag.Content = str2.tekstHTML.Replace("~", "..");
                ViewBag.Route = "Home -> " + str2.nazwa;

                return View();
            }
        }
        
        public ActionResult Dodatki()
        {
            List<Dodatki> dodatki;
            using (var db = new janiakmeble_6Entities())
            {
                dodatki = (from D in db.Dodatki
                          orderby D.Nazwa
                          select D).OrderBy(n=>n.Nazwa).ToList();                
            }
            return View(dodatki);
        }
       
	}
}

JaniakMeble/JaniakMeble/Controllers/OfferController.cs
using JaniakMeble.DAL;
using JaniakMeble.Functions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JaniakMeble.Controllers
{
    public class OfferController : Controller
    {
        //
        // GET: /Offer/
        public ActionResult Index()
        {
            ViewBag.Title = "Kategorie";
            ViewBag.Route = "Oferta -> Kategorie";

            List<Kategorie> kategorie = new List<Kategorie>();
            using (var A = new janiakmeble_6Entities())
            {
                var B = A.Kategorie;
                foreach (var C in B)
                {
                    kategorie.Add(C);
                }
            }
            return View(kategorie.OrderBy(x => x.Nazwa));
        }

        public ActionResult Category(string id)
        {
            List<Meble> mebelki = new List<Meble>();

            mebelki = myDAL.GetMebleWKategorii(id);

           
            try
            {
                ViewBag.Title = mebelki.Select(A => A).First().Kategorie.Nazwa;
            }
            catch
            {
                Error.Universal("KuPa", RouteData);
                return View("PageError");
            }
            return View(mebelki);
        }

        public ActionResult Product(string id)
        {
            ViewBag.Title = "Nazwa produktu";
            ViewBag.Route = "Oferta -> Kategorie -> Nazwa Produktu";
            Meble mebelek = new Meble();
            mebelek = myDAL.GetMebelByName(id);


            ViewBag.Title = mebelek.Nazwa;
            
            return View(mebelek);
        }

        public ActionResult ProductGalery(string id)
        {
            Meble mebelek = new Meble();
            mebelek = myDAL.GetMebelByName(id);

            return View(mebelek);
        }
	}
}

JaniakMeble/JaniakMeble/Views/Catalog/Details.cshtml
@model JaniakMeble.DAL.Katalog

@{
    ViewBag.Title = string.Format("{0} ({1})", Model.Nazwa, Model.katalog_kategorie.Nazwa);
}

  
<div id="catalogDetailsMain">
    <p>
        @if(@Model.Opis != null)
        {
            <p>@Model.Opis</p>
        }
            
    </p>
    @foreach (var zdjecie in Model.katalog_zdjecia)
    {
        <div class="catalogDetailsPos">           
            
            <p>nr: @zdjecie.Numer_tkaniny</p>
            <img src="~/@zdjecie.Link" title="@zdjecie.Numer_tkaniny" />
        </div>
    }
</div>
<div id="showPhotoBackround">
    <div id="showPhoto">

    </div>
</div>
<script src="~/Scripts/galeria2.js" type="text/javascript"></script>

JaniakMeble/JaniakMeble/Views/Catalog/Index.cshtml
@model IEnumerable<JaniakMeble.DAL.Katalog>

@{
    ViewBag.Title = "Katalog tkanin";
}

@foreach (var kategoria in Model.Select(x => x.katalog_kategorie.Nazwa).Distinct())
{
    <h1>
        @kategoria
    </h1>
    <div class="catalogMain">
    @foreach (var katalog in Model.Where(x => x.katalog_kategorie.Nazwa == kategoria))
    {

        <div class="catalogPos">
            <a href="@Url.Action("Details", "Catalog", new { id = katalog.Nazwa })">
                <h3>@katalog.Nazwa</h3>
                @{
                    string stars = "";
                    switch (katalog.Gwiazdki)
                    {
                        case 1: stars = "1stars.png"; break;
                        case 2: stars = "2stars.png"; break;
                        case 3: stars = "3stars.png"; break;
                    }
                    stars = "Resources/Images/others/" + stars;
                 }

                <img class="stars" src="~/@stars"/>
                <img src="~/@katalog.katalog_zdjecia.First().Link" />
            </a>
        </div>

    }
    </div>
    
}

JaniakMeble/JaniakMeble/Views/Home/Dodatki.cshtml
@model List<JaniakMeble.DAL.Dodatki>

@foreach (var item in Model)
{
    <h2 id="@item.Nazwa">
        @item.Nazwa
    </h2>

    <p>@item.Opis</p>
    <center>
        <img src="../@item.Zdjecie" width="50%" alt="@item.Nazwa" />
    </center>
    <hr />
}

JaniakMeble/JaniakMeble/Views/Home/Index.cshtml
<div>
    @*@(new HtmlString(ViewBag.Content))*@
    <div id="approve-banner">
        @Html.Partial("_LeftBanner")
    </div>

    <div id="new-banner">
        @Html.Partial("_RightBanner")
    </div>
</div>

JaniakMeble/JaniakMeble/Views/Offer/Category.cshtml
@model IEnumerable<JaniakMeble.DAL.Meble>

@{
    ViewBag.Route = "Oferta -> Kategorie -> " + ViewBag.Title;
}

<div id="positionList">
@foreach (var mebel in Model)
{
    <div class="positionListPos">
        <a href="~/Offer/Product/@mebel.Nazwa">
            <div class="positionListImage">
                <img src="~/@mebel.ZdjeciaMebli.OrderBy(n=> n.Numer).First().Link" />
            </div>
            <div class="positionListName">
                <h3>@mebel.Nazwa</h3>

            </div>
            @*<div class="positionListDescript">
                @mebel.OpisKrotki
            </div>*@
           
        </a>
    </div>
}

JaniakMeble/JaniakMeble/Views/Offer/Index.cshtml
@model IEnumerable<JaniakMeble.DAL.Kategorie>

@{
    ViewBag.Title = "Nasze meble";
}

@{
    var lista = Model.ToList();
}



<div id="categoryList">
    @foreach (var M in Model)
    {
        <div id="categoryPos">
            <a href="Offer/Category/@M.Nazwa.ToString()" title="@M.Nazwa.ToString()">
                <p>@M.Nazwa.ToString()</p>
            </a>
        </div>
    }
</div>

JaniakMeble/JaniakMeble/Views/Offer/Product.cshtml
@model JaniakMeble.DAL.Meble



@{
    @*ViewBag.Route = "Oferta -> Kategorie -> " + Model.Kategorie != null ? Model.Kategorie.Nazwa : "Kategoria" + " -> " + ViewBag.Title;*@

ViewBag.Title = Model.Nazwa != null ? Model.Nazwa : "Nazwa";
}


<table id="ContentTableProduct">
    <tr>
@*-------------------------------------------------------------------------*@
        <td id="td1">
            <div id="zdjecieGlowne">
                <img src="~/@Model.ZdjeciaMebli.OrderBy(n => n.Numer).First().Link" />
            </div>
            <div id="zdjecieStrzalki">
                <img src="~/Resources/Images/others/arrow-left.png" alt="Poprzednie zdjęcie" id="galery_arrow_left"/>
                <img src="~/Resources/Images/others/arrow-right.png" alt="Następne zdjęcie" id="galery_arrow_right" />
            </div>
            <div id="zdjeciaPozostale">
                @if (Model.ZdjeciaMebli.Count > 0)
                {
                    foreach (var A in Model.ZdjeciaMebli.OrderBy(n => n.Numer).ToList().Take(8))
                    {
                        <img src="~/@A.Link" />
                    }                    
                }
            </div>  
            @if(Model.ZdjeciaMebli.Count > 8)
            {
                <a href="@Url.Action("ProductGalery","Offer", new { id = Model.Nazwa})"><img src="~/Resources/Images/others/more_photos.png" style="width:100%; border:none; box-shadow:none;" /></a>
            }
        </td>

        <td id="td2">
@*-------------------------------------------------------------------------*@
            <div id="opisProduct">
                <h1>Opis</h1>
                @if (Model.Opis != null)
                {
                    <p>
                        @(new HtmlString(@Model.Opis.ToString()))
                   </p>
                }
                else
                {
                   <p>b/d</p>
                }

               
            </div>
@*-------------------------------------------------------------------------*@
            <div id="wymiaryProduct">
                <h1>Wymiary</h1>
                @if (Model.Kategorie.NazwaEASY.ToLower() == "narozniki")
                {
                    <img src="~/Resources/Images/others/wymiaryNaroznik.jpg"/>
                }else if (Model.Kategorie.NazwaEASY.ToLower() == "kanapy" || Model.Kategorie.NazwaEASY.ToLower() == "wersalki")
                {
                     <img src="~/Resources/Images/others/wymiaryKanapa.jpg"/>
                }
                @if (Model.Wymiary != null)
                {
                    <p>
                        @(new HtmlString(@Model.Wymiary))
                    </p>
                }
                else
                {
                    <p>b/d</p>
                }
                
            </div>
@*-------------------------------------------------------------------------*@
            @if (Model.Kategorie.NazwaEASY.ToLower() == "narozniki")
            {
            <div id="stronyProduct">
                <h1>Strony</h1>
                <div id="stronyNaroznika">
                    <img src="~/Resources/Images/others/strona_lewa.jpg" />
                    <img src="~/Resources/Images/others/strona_prawa.jpg" />
                </div>
               <p>Przy zamówieniu prosimy podać na jaką stronę ma być narożnik</p>
            </div>            
            }
@*-------------------------------------------------------------------------*@
            <div id="tkaninyProduct">
                <h1>Wybór tkaniny</h1>
                <p>Nasza firma daje możliwość samodzielnego wyboru tkaniny. U nas to Klient wybiera spośród dziesiątek katalogów tkanin w jakim kolorze ma być jego mebel. Katalogi tkanin można znaleźć <a href="@Url.Action("Index", "Catalog")">tutaj</a> </p>
            </div>
</td >
    </tr >
    <tr >
      <td colspan="2">
          @*Sprawdzenie czy sa jakies cechy*@
          @if (Model.Dodatki.Count > 0)
            {
              <div id="dodatkiProduct">
                  <h1>Cechy</h1>

                  @foreach (var A in Model.Dodatki)
                  {
                      <div>
                          <h4>@A.Nazwa</h4>
                          <br />
                          <img src="~/@A.Zdjecie" />
                          <br />
                          <p>@A.Opis</p>

                      </div>
                  }
              </div>
          }
      </td>
    </tr>
   
</table>
<div id="showPhotoBackround">
    <div id="showPhoto">
        
    </div>
</div>
<script src="~/Scripts/galeria1.js" type="text/javascript"></script>

JaniakMeble/JaniakMeble/Views/Offer/ProductGalery.cshtml
@model JaniakMeble.DAL.Meble

@{
    ViewBag.Title = "Galeria produktu";
}


<div id="catalogDetailsMain">
    <p>
        @if (@Model.Opis != null)
        {
        <p>@Model.Nazwa - galeria produktu</p>
        }

        </p>
        @foreach (var zdjecie in Model.ZdjeciaMebli)
        {
            <div class="catalogDetailsPos">                               
                <img src="~/@zdjecie.Link" title="@Model.Nazwa - @zdjecie.Numer" />
            </div>
        }
    </div>
    <div id="showPhotoBackround">
        <div id="showPhoto">

        </div>
    </div>
    <script src="~/Scripts/galeria2.js" type="text/javascript"></script>

JaniakMeble/JaniakMeble/Views/Shared/PageError.cshtml
<center>
    <h2>Coś poszło nie tak</h2>
    <h2 style="font-size:50px;"><pre>(⌣_⌣”)</pre></h2>

    Zapisaliśmy ten błąd na stronie i spróbujemy coś z tym zrobić

</center>

JaniakMeble/JaniakMeble/Views/Shared/_Footer.cshtml
<table>
    <tr>
        <td>
            <a><p><p>Strona główna</p></a>
            <a><p>Oferta</p></a>
            <a><p>Meble kuchenne</p></a>
            <a><p>Sklrp-meble.eu</p></a>
        </td>
        <td>
            <a><p>Katalog tkanin</p></a>
            <a><p>Dodatki i standardy</p></a>
            <a><p>Instrukcja montażu</p></a>
        </td>
        <td>
            <a><p>Transport</p></a>
            <a><p>Gwarancja</p></a>
            <a><p>Zakupy na raty</p></a>
            <a><p>Kontakt</p></a>
        </td>
        <td>
            <p>Znajdź nas</p>
            <a href="https://plus.google.com/104549884622367625591" title="Nasz profil w Google+"><img src="~/Resources/images/icons/gplusmini.png" width="40" class="ImageButton" /></a>
            <a href="https://www.facebook.com/JaniakMeble" title="Nasza społeczność na Facebook'u"><img src="~/Resources/images/icons/fbmini.png" width="40" class="ImageButton" /></a>
            <a href="http://allegro.pl/listing/user/listing.php?us_id=16160631&order=m" title="Nasze aukcje w serwisie Allegro"><img src="~/Resources/images/icons/allegromini.png" width="40" class="ImageButton" /></a>
        </td>
        <td>
            <p>Wykonanie strony</p>
            <a href="http://dosomething.pl" title="Wykonanie strony doSomething.pl"><img src="~/Resources/images/bigicons/dosomething.png" height="70" class="ImageButton"/></a>
        </td>
    </tr>
</table>

JaniakMeble/JaniakMeble/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Janiak-Meble @ViewBag.Title - producent mebli w okolicy Wrocławia</title>
    <link rel="Shortcut icon" href="~/Resources/Images/Icons/mainIcon.ico">
    <link href='http://fonts.googleapis.com/css?family=Andika&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Almendra&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-2" />
    <link href='http://fonts.googleapis.com/css?family=Archivo+Narrow&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
 
    <link href='~/styles/main.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/menu.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/header.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/content.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/foother.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/product.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/category.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/photoShower.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/katalog.css' rel='stylesheet' type='text/css'>
    <link href='~/styles/banners.css' rel='stylesheet' type='text/css'>

</head>
<body> <center>
    <div id="fb-root"></div>
    @*<script>
        (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.9";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));</script>*@
    
    <table id="mainBlockTable">
        <tr>
            <td id="leftTinyBarTd"></td>
            <td id="leftBarTd">
                @*<div id="menu">
                    @Html.Partial("_Menu")
                </div>*@
            </td>

            <td id="contentTd">
                <!--CONTENT-->
                <div id="header">
                    <div id="baner">

                        <p id="numer">tel. 695 532 980</p>
                        <p id="email">biuro@janiakmeble.pl</p>
                        <p id="head">@ViewBag.Title</p>
                    </div>
                    <div id="logo">
                        <a href="@Url.Action("Index", "Home")"><img src="~/Resources/images/others/logo_big2.png"></a>
                    </div>
                </div>
                <!--<img src="header.png" class="content"/>-->
               
                <div id="menu">
                    @Html.Partial("_Menu")
                </div>
                

                <div id="content">
                    @*<p>@ViewBag.Route</p>*@

                    <div>
                        @RenderBody()
                    </div>
                    @*<div class="fb-comments" data-href="https://www.facebook.com/JaniakMeble" data-width="100%" data-numposts="2"></div>*@
                </div>
                <div id="footer">
                    @Html.Partial("_Footer")
                </div>
                <!--ENDCONTERT-->
            </td>
        </tr>
    </table>
    @RenderSection("scripts", required: false)
          
</center>
    @*<script>

        document.getElementsByTagName('body')[0].innerHTML = document.getElementsByTagName('body')[0].innerHTML.replace("Allegro", "<p style=\"color:red;\">Allegro</p>");
    </script>*@

    </body>

</html>

JaniakMeble/JaniakMeble/Views/Shared/_LeftBanner.cshtml
<div class="banner left-banner">
    <img src="http://www.janiakmeble.pl/galeria/narozniki/rubin/nar_rubin2/img/photos/PA181234.JPG"/>
    <h1>Polecamy</h1>
    <h2>Narożnik Rubin II</h2>
    <a href="#">Sprawdź</a>
</div>

JaniakMeble/JaniakMeble/Views/Shared/_Menu.cshtml
<ul>
    <li><a href=@Url.Action("Index", "Offer")>Meble</a></li>
    <li><a href=#>Nasze realizacje</a></li>
    <li><a href=#>Akcesoria meblowe</a></li>
    <li><a href=@Url.Action("Index", "Catalog")>Katalogi tkanin</a></li>
    <li><a href=#>Kontakt</a></li>
</ul>

JaniakMeble/JaniakMeble/Views/Shared/_RightBanner.cshtml
<div class="banner right-banner">
    <img src="http://janiakmeble.pl/galeria/narozniki/rubin/nar_rubin4/img/photos/P9221412.JPG"/>
    <h1>Nowość</h1>
    <h2>Narożnik Rubin III</h2>
    <a href="#">Sprawdź</a>
</div>